name: Semantic release

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: portolacommon
  GAR_LOCATION: us-west1

jobs:
  release:
    permissions:
#      contents: 'read'
      contents: 'write'
      id-token: 'write'

    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    concurrency:
      group: ONE_RELEASE_AT_A_TIME
      cancel-in-progress: false
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v5'

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: 'Semantic Release'
        id: semantic_dry_run
        uses: cycjimmy/semantic-release-action@v5
        with:
          branches: |
            ['main']
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_DRAGON }}
