name: Semantic release

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: portolacommon
  GAR_LOCATION: us-west1

jobs:
  release:
    permissions:
#      contents: 'read'
      contents: 'write'
      id-token: 'write'

    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-24.04
    concurrency:
      group: ONE_RELEASE_AT_A_TIME
      cancel-in-progress: false
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@v4'

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: 'Semantic Release'
        id: semantic_dry_run
        uses: cycjimmy/semantic-release-action@v4
        with:
          branches: |
            ['main']
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Do something when a new release published
        if: steps.semantic_dry_run.outputs.new_release_published == 'true'
        run: |
          echo "Last release:" ${{ steps.semantic_dry_run.outputs.last_release_version }}
          echo "New release: " ${{ steps.semantic_dry_run.outputs.new_release_version }}

      - name: 'Check if release was made'
        if: steps.semantic_dry_run.outputs.new_release_published == 'false'
        run: |
          echo "Last release: "
          echo ${{ steps.semantic_dry_run.outputs.last_release_version }}
          exit 1
